### PR TITLE
Simple models methods #52

### LINKED ISSUE #52: Add new __str__ and __repr__ method to other SimpleModels
**Description of feature/enhancement**
New string and representation method was created that leverages the npEncoder. Add this implementation to all SimpleModel classes:
https://github.com/skekre98/simple_learn/blob/39f1674ebee90f2bc5df36b4c933a2021addeae4/simple_learn/encoders/simple_model_encoder.py#L26-L30

**Description of implementation**
Implementation will essentially be the same as in SimpleClassifier:
```python
def __str__(self):

    for k in self.attributes:
        if type(self.attributes[k]) == np.int64:
            self.attributes[k] = int(self.attributes[k])

    attr = {
        "Type": self.name,
        "Training Duration": "{}s".format(self.train_duration),
        "GridSearch Duration": "{}s".format(self.gridsearch_duration),
        "Parameters": self.attributes,
        "Metrics": self.metrics,
    }

    str_out = json.dumps(attr, cls=simple_model_encoder.npEncoder, indent=4)
    return str_out

def __repr__(self):

    attr = {
        "Type": self.name,
        "Training Duration": "{}s".format(self.train_duration),
        "GridSearch Duration": "{}s".format(self.gridsearch_duration),
        "Parameters": self.attributes,
        "Metrics": self.metrics,
    }

    repr_out = json.dumps(attr, cls=simple_model_encoder.npEncoder, indent=4)
    return repr_out
```

**Why this is a good feature/enhancement**
This will allow users to visualize the results and metrics of their models.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by Turtle24**
The SimpleRegressor Class in the ```simple_regressor.py``` and the SimpleClassifierListObject Class in the ```simple_classifier_list.py``` have ```__str__``` and ```__repr__``` methods and they're using the ```simple_model_encoder``` now as requested in #52. Is this ok or do I need to change or add anything else?

***SimpleRegressor Class - output in python shell***

```
>>> from sklearn.datasets import load_boston
>>> from simple_learn.regressors import SimpleRegressor
>>> boston = load_boston() 
>>> true_x = boston.data   
>>> true_y = boston.target 
>>> clf = SimpleRegressor()
>>> clf.fit(true_x, true_y)
>>> clf
{
    "Type": "GradientBoostingRegressor",
    "Training Duration": "0.035027265548706055s",
    "GridSearch Duration": "42.975895404815674s",
    "Parameters": {
        "criterion": "mse",
        "learning_rate": 0.1,
        "loss": "ls",
        "max_depth": 3,
        "max_features": "sqrt",
        "n_estimators": 100
    },
    "Metrics": {
        "Training Score": 4.588113116187022,
        "Mean Absolute Error": 1.2970164361965444,
        "Mean Square Error": 2.8097807626515943,
        "R-Squared": 0.966716470796721
    }
}
>>> print(clf) 
{
    "Type": "GradientBoostingRegressor",
    "Training Duration": "0.035027265548706055s",
    "GridSearch Duration": "42.975895404815674s",
    "Parameters": {
        "criterion": "mse",
        "learning_rate": 0.1,
        "loss": "ls",
        "max_depth": 3,
        "max_features": "sqrt",
        "n_estimators": 100
    },
    "Metrics": {
        "Training Score": 4.588113116187022,
        "Mean Absolute Error": 1.2970164361965444,
        "Mean Square Error": 2.8097807626515943,
        "R-Squared": 0.966716470796721
    }
}
```
***The SimpleClassifierListObject Class  - output in python shell***

```
>>> from sklearn.datasets import load_iris
>>> from simple_learn.classifiers import SimpleClassifier
>>> from simple_learn.classifiers import SimpleClassifierListObject
>>>
>>> iris = load_iris()
>>> clf = SimpleClassifier()
>>> clf.fit(iris.data, iris.target)
>>> clf.fit(iris.data, iris.target)
>>> clfobj = SimpleClassifierListObject(clf, 1)
>>> clfobj
{
    "Type": "KNeighborsClassifier",
    "Rank": 1,
    "Training Duration": "0.0010004043579101562s",
    "GridSearch Duration": "0.11245250701904297s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    },
    "Index": 0
}
>>> print(clfobj) 
{
    "Type": "KNeighborsClassifier",
    "Rank": 1,
    "Training Duration": "0.0010004043579101562s",
    "GridSearch Duration": "0.11245250701904297s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    },
    "Index": 0
}
```

### CODE REVIEW

**Review by skekre98 — APPROVED** [review]
@Turtle24 This is excellent work! Would you also mind adding this in `SimpleClassifierList` or would you like me to go ahead and merge this as is now?

**Comment by Turtle24** [comment]
> @Turtle24 This is excellent work! Would you also mind adding this in `SimpleClassifierList` or would you like me to go ahead and merge this as is now?
I had a feeling I might of missed something, @skekre98  I'll update it quick. Rather have everything all done at once.

**Comment by Turtle24** [comment]
@skekre98 the SimpleClassifierList was throwing a KeyError and I've been trying to figure it out so I can do the methods for it. So I tried out the BaseException you mentioned for the SimpleRegressor and it shows euclidean being passed into the metric_map[scoring]. Or atleast that's what I think is happening but any pointers would help.

This is what puts out the logging in the python shell below. I gave the BaseExcepting a try in the SimpleClassifierList Class.

```python
def __init__(self, scoring="auto"):
        self.ranked_list = []
        self.failed_metric = []
        self.logger = logging.getLogger()

        metric_map = {
            "auto": "Training Accuracy",
            "jaccard": "Jaccard Score",
            "f1": "F1 Score",
        }
        try:
            self.metric = metric_map[scoring]

        except BaseException as error:
            self.failed_metric.append(scoring) 
            self.logger.warning(f"{scoring} failed, Error : {error}") 
```
Here's the python shell output:
```
>>> from sklearn.datasets import load_iris
>>> from simple_learn.classifiers import SimpleClassifier
>>> from simple_learn.classifiers import SimpleClassifierList, SimpleClassifierListObject
>>>
>>> iris = load_iris()
>>> clf = SimpleClassifier()
>>> clf.fit(iris.data, iris.target)
>>> clfobj = SimpleClassifierListObject(clf, 1)
>>> clflst = SimpleClassifierList(clfobj)
{
    "Type": "KNeighborsClassifier",
    "Rank": 1,
    "Training Duration": "0.0010008811950683594s",
    "GridSearch Duration": "0.11402630805969238s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    },
    "Index": 0
} failed, Error : {
    "Type": "KNeighborsClassifier",
    "Rank": 1,
    "Training Duration": "0.0010008811950683594s",
    "GridSearch Duration": "0.11402630805969238s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    },
    "Index": 0
}
>>>
```

**Comment by skekre98** [comment]
@Turtle24 I think the error is being caused because you are passing an object of type `SimpleClassifierListObject` when creating your classifier list, but this input parameter does not exist in its `__init__` function. The only input parameter `SimpleClassifierList` takes is _scoring_ which is of type `str`.

Out of curiosity, why was this added? I don't see any benefit to this. 
```python
try:
    self.metric = metric_map[scoring]
except BaseException as error:
    self.failed_metric.append(scoring) 
    self.logger.warning(f"{scoring} failed, Error : {error}") 
```

**Comment by Turtle24** [comment]
@skekre98 Ok I see where I went wrong. Sorry I went off the beaten track completely and tunnel visioned. So if you call the ClassifierList and the it's empty it returns the string "The List is Empty!". Once the ClassifierList contains the list it returns the ranked list as expected. ***I trimmed the ranked list return so this comment isn't super long***

```python
    def __str__(self):
        r = 1
        res = []
        for clf in self.ranked_list:
            obj = SimpleClassifierListObject(clf, r)
            res.append(str(obj))
            r += 1
        return "\n".join(res) if len(res) > 1 else "The List is Empty!"

    def __repr__(self):
        r = 1
        res = []
        for clf in self.ranked_list:
            obj = SimpleClassifierListObject(clf, r)
            res.append(str(obj))
            r += 1
        return "\n".join(res) if len(res) > 1 else "The List is Empty!"
```

```
>>> from sklearn.datasets import load_iris
>>> from simple_learn.classifiers import SimpleClassifier
>>> from simple_learn.classifiers import SimpleClassifierList, SimpleClassifierListObject
>>>
>>> iris = load_iris()
>>> clf_list = SimpleClassifierList()
>>> print(clf_list) 
The List is Empty!
>>> clf_list
The List is Empty!
>>> true_x = iris.data
>>> true_y = iris.target
>>> clf_list.fit(true_x, true_y)
>>> clf_list
{
    "Type": "KNeighborsClassifier",
    "Rank": 1,
    "Training Duration": "0.00099945068359375s", 
    "GridSearch Duration": "0.1070246696472168s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    },
    "Index": 0
}
{
    "Type": "DecisionTreeClassifier",
    "Rank": 2,
    "Training Duration": "0.001001119613647461s",
    "GridSearch Duration": "0.14803361892700195s",
    "Parameters": {
        "criterion": "gini",
        "max_depth": 3
    },
    "Metrics": {
        "Training Accuracy": 0.9733333333333333,
        "Jaccard Score": 0.9486989764459243,
        "F1 Score": 0.9733226623982927
    },
    "Index": 1
}
{
    "Type": "ExtraTreeClassifier",
    "Rank": 3,
    "Training Duration": "0.0s",
    "GridSearch Duration": "0.07901978492736816s",
    "Parameters": {
        "criterion": "gini",
        "max_depth": 9,
        "splitter": "best"
    },
    "Metrics": {
        "Training Accuracy": 0.9666666666666667,
        "Jaccard Score": 1.0,
        "F1 Score": 1.0
    },
    "Index": 2
}
{
    "Type": "ComplementNB",
    "Rank": 11,
    "Training Duration": "0.0010006427764892578s",
    "GridSearch Duration": "0.02600407600402832s",
    "Parameters": {
        "alpha": 0.1,
        "fit_prior": true,
        "norm": false
    },
    "Metrics": {
        "Training Accuracy": 0.6666666666666666,
        "Jaccard Score": 0.4951475539710834,
        "F1 Score": 0.5537466498327684
    },
    "Index": 10
}
>>> print(clf_list) 
{
    "Type": "KNeighborsClassifier",
    "Rank": 1,
    "Training Duration": "0.00099945068359375s",
    "GridSearch Duration": "0.1070246696472168s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    },
    "Index": 0
}
{
    "Type": "DecisionTreeClassifier",
    "Rank": 2,
    "Training Duration": "0.001001119613647461s",
    "GridSearch Duration": "0.14803361892700195s",
    "Parameters": {
        "criterion": "gini",
        "max_depth": 3
    },
    "Metrics": {
        "Training Accuracy": 0.9733333333333333,
        "Jaccard Score": 0.9486989764459243,
        "F1 Score": 0.9733226623982927
    },
    "Index": 1
}
{
    "Type": "ExtraTreeClassifier",
    "Rank": 3,
    "Training Duration": "0.0s",
    "GridSearch Duration": "0.07901978492736816s",
    "Parameters": {
        "criterion": "gini",
        "max_depth": 9,
        "splitter": "best"
    },
    "Metrics": {
        "Training Accuracy": 0.9666666666666667,
        "Jaccard Score": 1.0,
        "F1 Score": 1.0
    },
    "Index": 2
{
    "Type": "ComplementNB",
    "Rank": 11,
    "Training Duration": "0.0010006427764892578s",
    "GridSearch Duration": "0.02600407600402832s",
    "Parameters": {
        "alpha": 0.1,
        "fit_prior": true,
        "norm": false
    },
    "Metrics": {
        "Training Accuracy": 0.6666666666666666,
        "Jaccard Score": 0.4951475539710834,
        "F1 Score": 0.5537466498327684
    },
    "Index": 10
}
>>>
}
```

**Comment by skekre98** [comment]
@Turtle24 Awesome, that sounds good to me. Once you push those changes, I'll go ahead and merge the PR.

**Pull request merged**
