### PR TITLE
Simple objects logging

### LINKED ISSUE #48: Issues with logging SimpleObjects to terminal
**Describe the bug**
TypeError: Object of type int32 is not JSON serializable when trying to fit the iris dataset with the SimpleClassier. 

**To Reproduce**
1. Go to 'python terminal'
2. Run 'attempt the demo from the ReadMe'

**Expected behavior**
Expected the SimpleClassifier to fit the Iris dataset.

**Screenshots**
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aidan\simple_learn\simple_learn\classifiers\simple_classifier.py", line 85, in __str__     
    return json.dumps(attr, indent=4)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps     
    return cls(
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 201, in encode     
    chunks = list(chunks)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Aidan\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int32 is not JSON serializable
>>>
'''

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: [e.g. 0.0.1]

**Additional context**
json.dumps() doesn't handle int32 and requires an int for the required output.

### LINKED ISSUE #50: SimpleModel Encoder
**Description of feature/enhancement**
Implement encoder class for SimpleModels so they can be leveraged in methods such as` __str__` and `__repr__`.

**Description of implementation**
Don't have anything specific in mind at the moment, but we will need to handle cases such as type conversion.

**Why this is a good feature/enhancement**
This will allow us to encode general purpose SimpleModel information in a separate module.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by Turtle24**
The PR contains both #48 and #50 issues. #48 requires #50 feature to avoid the truncation that was occuring. Simple objects logging bug fix was a change to the ```SimpleClassifier``` class, the ```__str__``` and ```__repr__```  were changed to give the desired output. The Encoder feature is used by the ``` __str__``` and ``` __repr__``` methods to avoid the TypeError: Object of type 'int32' and also prevent truncation.

```python
>>> from sklearn.datasets import load_iris
>>> iris = load_iris()
>>> import simple_learn
>>> from simple_learn.classifiers import SimpleClassifier
>>> clf = SimpleClassifier()
>>> clf.fit(iris.data, iris.target) 
>>> clf
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0009996891021728516s",
    "GridSearch Duration": "0.12402796745300293s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
>>> print(clf) 
{
    "Type": "KNeighborsClassifier",
    "Training Duration": "0.0009996891021728516s",
    "GridSearch Duration": "0.12402796745300293s",
    "Parameters": {
        "metric": "euclidean",
        "n_neighbors": 4,
        "weights": "uniform"
    },
    "Metrics": {
        "Training Accuracy": 0.9866666666666667,
        "Jaccard Score": 0.9245283018867925,
        "F1 Score": 0.96
    }
}
```

### CODE REVIEW

**Comment by skekre98** [comment]
@Turtle24 you can fix the Static errors by running `pre-commit run --all-files`, this will lint/format your code. See the contributing section in the README for more info :)

**Review by skekre98 — APPROVED** [review]
Great work @Turtle24! Can you also add the log output of the `__str__` and `__repr__` methods to the PR description to keep a record of it?

**Comment by Turtle24** [comment]
> Great work @Turtle24! Can you also add the log output of the `__str__` and `__repr__` methods to the PR description to keep a record of it?

Thanks @skekre98 😁 Updated, is that fine? Also I had to do a bit of a git crash course there haha, I'll be using gitbash more now though :D

**Comment by skekre98** [comment]
@Turtle24 looks great! I'll go ahead and merge the PR.

**Pull request merged**
