### PR TITLE
Add unique test cases to SimpleClassifierList #30

### PR DESCRIPTION
**Pull request by eranns**
Added more classification tests from sklearn.datasets as much as my computer could handle.

### CODE REVIEW

**Comment by skekre98** [comment]
Hi @eranns, seems the pre-commit checks are failing. Can you try running the following steps:
1.  `./scripts/setup.sh`
2. `pre-commit run --all-files`

This will lint and format the code for you.

**Comment by eranns** [comment]
> Hi @eranns, seems the pre-commit checks are failing. Can you try running the following steps:
> 
> 1. `./scripts/setup.sh`
> 2. `pre-commit run --all-files`
> 
> This will lint and format the code for you.

Hi

I did but it only fixing README for some reason and there's nothing to commit besides that. heres the output

```
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing README.md

Fix python encoding pragma...............................................Passed
Add license to all executable files......................................Passed
Black....................................................................Passed
Run isort to sort imports................................................Passed

```

**Comment by eranns** [comment]
> > Hi @eranns, seems the pre-commit checks are failing. Can you try running the following steps:
> > 
> > 1. `./scripts/setup.sh`
> > 2. `pre-commit run --all-files`
> > 
> > This will lint and format the code for you.
> 
> Hi
> 
> I did but it only fixing README for some reason and there's nothing to commit besides that. heres the output
> 
I see now that my last commit of the pre commit changes work. I will try to fix it in the morning.

**Comment by eranns** [comment]
OK. I looked on it. 

I thought the last commit of lint changes did not work but the log says it's failing in the README.md file which I didn't modify. do you want me to add it to the PR or solve it other way ?

**Comment by skekre98** [comment]
> I thought the last commit of lint changes did not work but the log says it's failing in the README.md file which I didn't modify. do you want me to add it to the PR or solve it other way ?

Yea, please go ahead and add it to this PR 👍

**Review by skekre98 — APPROVED** [review]
Great work @eranns! I'll go ahead and merge the PR.

**Pull request merged**
